In [1]:
import pandas as pd
import numpy as np
import psycopg2
from sqlalchemy import create_engine

In [2]:
engine = create_engine("postgresql://root:root@localhost:5432/telecom_churn")

In [3]:
df = pd.read_sql("SELECT * FROM telecom_churn", engine)

In [4]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

***DATA PREPARATION***

In [5]:
# check for missing values
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [6]:
# type of each column
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [7]:
# convert totalcharges to numeric, coerce errors to NaN
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")
# check for missing values again
df.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [8]:
# drop rows with missing values
df.dropna(inplace=True)
# check for missing values again
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [9]:
# remove customerID column as it is not useful for prediction
df.drop('customerID', axis=1, inplace=True)

In [10]:
# drop insignificant columns
df = df.drop(columns=["gender", "PhoneService"])

In [11]:
# encoding categorical variables
df['SeniorCitizen'] = df['SeniorCitizen'].astype('category')  # Ensure SeniorCitizen is treated as categorical
df_encoded = pd.get_dummies(df, drop_first=True)
df_encoded.head()

,tenure,MonthlyCharges,TotalCharges,SeniorCitizen_1,Partner_Yes,Dependents_Yes,MultipleLines_No phone service,MultipleLines_Yes,InternetService_Fiber optic,InternetService_No,...,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,Churn_Yes
0,1,29.85,29.85,False,True,False,True,False,False,False,...,False,False,False,False,False,True,False,True,False,False
1,34,56.95,1889.50,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,True,False
2,2,53.85,108.15,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,True,True
3,45,42.30,1840.75,False,False,False,True,False,False,False,...,False,False,False,True,False,False,False,False,False,False
4,2,70.70,151.65,False,False,False,False,False,True,False,...,False,False,False,False,False,True,False,True,False,True

In [12]:
df_encoded.dtypes

tenure                                     int64
MonthlyCharges                           float64
TotalCharges                             float64
SeniorCitizen_1                             bool
Partner_Yes                                 bool
Dependents_Yes                              bool
MultipleLines_No phone service              bool
MultipleLines_Yes                           bool
InternetService_Fiber optic                 bool
InternetService_No                          bool
OnlineSecurity_No internet service          bool
OnlineSecurity_Yes                          bool
OnlineBackup_No internet service            bool
OnlineBackup_Yes                            bool
DeviceProtection_No internet service        bool
DeviceProtection_Yes                        bool
TechSupport_No internet service             bool
TechSupport_Yes                             bool
StreamingTV_No internet service             bool
StreamingTV_Yes                             bool
StreamingMovies_No internet service         bool
StreamingMovies_Yes                         bool
Contract_One year                           bool
Contract_Two year                           bool
PaperlessBilling_Yes                        bool
PaymentMethod_Credit card (automatic)       bool
PaymentMethod_Electronic check              bool
PaymentMethod_Mailed check                  bool
Churn_Yes                                   bool
dtype: object

In [13]:
# convert target variable to binary
df_encoded['Churn_Yes'] = df_encoded['Churn_Yes'].astype(int)

***DATA SPLIT***

In [14]:
df_encoded.head()

,tenure,MonthlyCharges,TotalCharges,SeniorCitizen_1,Partner_Yes,Dependents_Yes,MultipleLines_No phone service,MultipleLines_Yes,InternetService_Fiber optic,InternetService_No,...,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,Churn_Yes
0,1,29.85,29.85,False,True,False,True,False,False,False,...,False,False,False,False,False,True,False,True,False,0
1,34,56.95,1889.50,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,True,0
2,2,53.85,108.15,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,True,1
3,45,42.30,1840.75,False,False,False,True,False,False,False,...,False,False,False,True,False,False,False,False,False,0
4,2,70.70,151.65,False,False,False,False,False,True,False,...,False,False,False,False,False,True,False,True,False,1

In [15]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
import xgboost as xgb
from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve
from sklearn.metrics import auc
import matplotlib.pyplot as plt
import seaborn as sns

In [16]:
X = df_encoded.drop(columns=["Churn_Yes"])
y = df_encoded["Churn_Yes"]

In [18]:
for col in X.select_dtypes(include="bool"):
    X[col] = X[col].astype(int)

In [19]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [20]:
X_train.head()

,tenure,MonthlyCharges,TotalCharges,SeniorCitizen_1,Partner_Yes,Dependents_Yes,MultipleLines_No phone service,MultipleLines_Yes,InternetService_Fiber optic,InternetService_No,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
1413,65,94.55,6078.75,0,1,1,0,1,1,0,...,0,0,0,0,0,1,0,1,0,0
7003,26,35.75,1022.50,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3355,68,90.20,6297.65,0,1,0,0,1,1,0,...,0,0,0,0,0,1,0,1,0,0
4494,3,84.30,235.05,0,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
3541,49,40.65,2070.75,0,1,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [21]:
X_train.dtypes

tenure                                     int64
MonthlyCharges                           float64
TotalCharges                             float64
SeniorCitizen_1                            int64
Partner_Yes                                int64
Dependents_Yes                             int64
MultipleLines_No phone service             int64
MultipleLines_Yes                          int64
InternetService_Fiber optic                int64
InternetService_No                         int64
OnlineSecurity_No internet service         int64
OnlineSecurity_Yes                         int64
OnlineBackup_No internet service           int64
OnlineBackup_Yes                           int64
DeviceProtection_No internet service       int64
DeviceProtection_Yes                       int64
TechSupport_No internet service            int64
TechSupport_Yes                            int64
StreamingTV_No internet service            int64
StreamingTV_Yes                            int64
StreamingMovies_No internet service        int64
StreamingMovies_Yes                        int64
Contract_One year                          int64
Contract_Two year                          int64
PaperlessBilling_Yes                       int64
PaymentMethod_Credit card (automatic)      int64
PaymentMethod_Electronic check             int64
PaymentMethod_Mailed check                 int64
dtype: object

In [22]:
y.head()

0    0
1    0
2    1
3    0
4    1
Name: Churn_Yes, dtype: int64

In [23]:
# fix threshold 
from pyexpat import model

model = LogisticRegression(class_weight='balanced', max_iter=5000)
model.fit(X_train, y_train)
y_proba=model.predict_proba(X_test)[:, 1] # get probabilities for the positive class
threshold = 0.3
y_pred = (y_proba >= threshold).astype(int) # convert probabilities to binary predictions
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.96      0.54      0.69      1033
           1       0.42      0.93      0.58       374

    accuracy                           0.64      1407
   macro avg       0.69      0.73      0.63      1407
weighted avg       0.81      0.64      0.66      1407

In [24]:
# fix threshold 
from pyexpat import model

model = LogisticRegression(class_weight='balanced', max_iter=5000)
model.fit(X_train, y_train)
y_proba=model.predict_proba(X_test)[:, 1] # get probabilities for the positive class
threshold = 0.5
y_pred = (y_proba >= threshold).astype(int) # convert probabilities to binary predictions
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.91      0.71      0.80      1033
           1       0.50      0.80      0.61       374

    accuracy                           0.73      1407
   macro avg       0.70      0.75      0.71      1407
weighted avg       0.80      0.73      0.75      1407

| Model | Recall (churn) | Precision (churn) | Accuracy |
| :--- | :---: | :---: | :---: |
| Default (0.5) | 0.58 | 0.65 | 0.81 |
| Lower threshold (0.3) | 0.93 | 0.42 | 0.64 |
| **Balanced (this one)** | **0.80** | **0.50** | **0.73** |

precision = mabin dkchi li predictinah positive chhal positive bss7 = mabin dkchi li predictinah churn hoa many churn bssh

recall = mabin dkchi li positive bssh chhal mn wahd detectina = mabin churn people how many are predicted churn

ana bghit wakha tkon machi churn npredictik churn donc ntle3 recall

In [26]:
import mlflow
import mlflow.sklearn

In [32]:
mlflow.set_experiment("telecom-churn-prediction")

<Experiment: artifact_location='/workspaces/Telecom-Churn-Prediction/notebooks/mlruns/1', creation_time=1774705605413, experiment_id='1', last_update_time=1774705605413, lifecycle_stage='active', name='telecom-churn-prediction', tags={}, workspace='default'>

In [36]:
print(mlflow.get_tracking_uri())

sqlite:////workspaces/Telecom-Churn-Prediction/notebooks/mlflow.db

In [37]:
mlflow.set_tracking_uri("http://127.0.0.1:5000")

In [38]:
print(mlflow.get_tracking_uri())

http://127.0.0.1:5000

In [40]:
mlflow.set_experiment("telecom-churn-prediction")

2026/03/28 14:02:38 INFO mlflow.tracking.fluent: Experiment with name 'telecom-churn-prediction' does not exist. Creating a new experiment.

<Experiment: artifact_location='mlflow-artifacts:/1', creation_time=1774706558632, experiment_id='1', last_update_time=1774706558632, lifecycle_stage='active', name='telecom-churn-prediction', tags={}, workspace='default'>

In [54]:
from sklearn.metrics import (
    classification_report, recall_score,
    precision_score, f1_score, roc_auc_score,accuracy_score
)



with mlflow.start_run(run_name="lr_baseline"):

    # --- Train ---
    model = LogisticRegression(max_iter=5000, random_state=42)
    model.fit(X_train, y_train)

    # --- Predict ---
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:, 1]

    # --- Compute metrics ---
    recall    = recall_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    f1        = f1_score(y_test, y_pred)
    roc_auc   = roc_auc_score(y_test, y_prob)
    accuracy_score = accuracy_score(y_test, y_pred)

    # --- Log parameters (what went IN) ---
    mlflow.log_param("model","LogisticRegression")
    mlflow.log_param("C",1.0)
    mlflow.log_param("class_weight", "none")
    mlflow.log_param("threshold",    0.5)

    # --- Log metrics (what came OUT) ---
    mlflow.log_metric("recall",    recall)
    mlflow.log_metric("precision", precision)
    mlflow.log_metric("accuracy",  accuracy_score)
    mlflow.log_metric("f1_score",  f1)
    mlflow.log_metric("roc_auc",   roc_auc)

    # --- Log the model itself ---
    # This saves the trained model so you can reload it later without retraining
    mlflow.sklearn.log_model(model, artifact_path="model")

    print(classification_report(y_test, y_pred, target_names=["No Churn", "Churn"]))
    print(f"ROC-AUC: {roc_auc:.3f}")

2026/03/28 14:36:50 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/03/28 14:36:51 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/03/28 14:36:54 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.

              precision    recall  f1-score   support

    No Churn       0.85      0.89      0.87      1033
       Churn       0.65      0.58      0.61       374

    accuracy                           0.81      1407
   macro avg       0.75      0.73      0.74      1407
weighted avg       0.80      0.81      0.80      1407

ROC-AUC: 0.841
🏃 View run lr_baseline at: http://127.0.0.1:5000/#/experiments/1/runs/0fa5722927874cb29c3eefd22887541a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

In [56]:
from sklearn.metrics import (
    classification_report, recall_score,
    precision_score, f1_score, roc_auc_score,accuracy_score
)

with mlflow.start_run(run_name="lr_balanced"):
    lr_balanced=LogisticRegression(class_weight='balanced',max_iter=5000)
    lr_balanced.fit(X_train,y_train)
    
    y_pred=lr_balanced.predict(X_test)
    y_proba=lr_balanced.predict_proba(X_test)[:, 1]
    accuracy_score = accuracy_score(y_test, y_pred)
    
    mlflow.log_metric("recall",recall_score(y_test,y_pred))
    mlflow.log_metric("precision", precision_score(y_test, y_pred))
    mlflow.log_metric("accuracy", accuracy_score)
    mlflow.log_metric("f1_score", f1_score(y_test, y_pred))
    mlflow.log_metric("roc_auc", roc_auc_score(y_test, y_proba))
    
    mlflow.log_param("model", "LogisticRegression")
    mlflow.log_param("class_weight", "balanced")
    mlflow.log_param("max_iter", 5000)
    mlflow.log_param("threshold", 0.5)
    mlflow.log_param("C", 1.0)
    
    mlflow.sklearn.log_model(lr_balanced, artifact_path="model")
    print(classification_report(y_test, y_pred, target_names=["No Churn", "Churn"]))
    print(f"ROC-AUC: {roc_auc_score(y_test, y_proba):.3f}")

2026/03/28 14:38:28 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/03/28 14:38:28 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/03/28 14:38:33 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.

              precision    recall  f1-score   support

    No Churn       0.91      0.71      0.80      1033
       Churn       0.50      0.80      0.61       374

    accuracy                           0.73      1407
   macro avg       0.70      0.75      0.71      1407
weighted avg       0.80      0.73      0.75      1407

ROC-AUC: 0.840
🏃 View run lr_balanced at: http://127.0.0.1:5000/#/experiments/1/runs/b4a03a5590f44acda9bd1b10005ef384
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

In [57]:
from sklearn.metrics import (
    classification_report, recall_score,
    precision_score, f1_score, roc_auc_score,accuracy_score
)

with mlflow.start_run(run_name="lr_balanced_threshold_0.3"):
    lr_balanced=LogisticRegression(class_weight='balanced',max_iter=5000)
    lr_balanced.fit(X_train,y_train)
    
    y_proba=lr_balanced.predict_proba(X_test)[:, 1]
    y_pred=(y_proba >= 0.3).astype(int)
    
    mlflow.log_metric("recall",recall_score(y_test,y_pred))
    mlflow.log_metric("precision", precision_score(y_test, y_pred))
    mlflow.log_metric("f1_score", f1_score(y_test, y_pred))
    mlflow.log_metric("roc_auc", roc_auc_score(y_test, y_proba))
    
    mlflow.log_param("model", "LogisticRegression")
    mlflow.log_param("class_weight", "balanced")
    mlflow.log_param("max_iter", 5000)
    mlflow.log_param("threshold", 0.3)
    mlflow.log_param("C", 1.0)
    
    mlflow.sklearn.log_model(lr_balanced, artifact_path="model")
    print(classification_report(y_test, y_pred, target_names=["No Churn", "Churn"]))
    print(f"ROC-AUC: {roc_auc_score(y_test, y_proba):.3f}")

2026/03/28 14:38:43 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/03/28 14:38:43 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/03/28 14:38:46 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.

              precision    recall  f1-score   support

    No Churn       0.96      0.54      0.69      1033
       Churn       0.42      0.93      0.58       374

    accuracy                           0.64      1407
   macro avg       0.69      0.73      0.63      1407
weighted avg       0.81      0.64      0.66      1407

ROC-AUC: 0.840
🏃 View run lr_balanced_threshold_0.3 at: http://127.0.0.1:5000/#/experiments/1/runs/b45060ebf2af49b38fb1159b3f2c02e9
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

In [58]:
from sklearn.metrics import (
    classification_report, recall_score,
    precision_score, f1_score, roc_auc_score,accuracy_score
)

with mlflow.start_run(run_name="lr_balanced_threshold_0.4"):
    lr_balanced=LogisticRegression(class_weight='balanced',max_iter=5000)
    lr_balanced.fit(X_train,y_train)
    
    y_proba=lr_balanced.predict_proba(X_test)[:, 1]
    y_pred=(y_proba >= 0.4).astype(int)
    
    mlflow.log_metric("recall",recall_score(y_test,y_pred))
    mlflow.log_metric("precision", precision_score(y_test, y_pred))
    mlflow.log_metric("f1_score", f1_score(y_test, y_pred))
    mlflow.log_metric("roc_auc", roc_auc_score(y_test, y_proba))
    
    mlflow.log_param("model", "LogisticRegression")
    mlflow.log_param("class_weight", "balanced")
    mlflow.log_param("max_iter", 5000)
    mlflow.log_param("threshold", 0.4)
    mlflow.log_param("C", 1.0)
    
    mlflow.sklearn.log_model(lr_balanced, artifact_path="model")
    print(classification_report(y_test, y_pred, target_names=["No Churn", "Churn"]))
    print(f"ROC-AUC: {roc_auc_score(y_test, y_proba):.3f}")

2026/03/28 14:39:17 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/03/28 14:39:17 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/03/28 14:39:20 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.

              precision    recall  f1-score   support

    No Churn       0.93      0.63      0.75      1033
       Churn       0.46      0.87      0.60       374

    accuracy                           0.69      1407
   macro avg       0.69      0.75      0.68      1407
weighted avg       0.80      0.69      0.71      1407

ROC-AUC: 0.840
🏃 View run lr_balanced_threshold_0.4 at: http://127.0.0.1:5000/#/experiments/1/runs/4ea72a1b51384a62bb4892b5195a2938
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1